### ISSUE TITLE
How do I add Apache POI Scratchpad module?

### ISSUE THREAD

**Issue by timkoers** [andruhon/android5xlsx#1]
When adding the scratchpad dependency (version 3.12) I get the following error when building the apk.

Error:Execution failed for task ':mobile:transformClassesWithJarMergingForDebug'.

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/apache/poi/EmptyFileException.class

Or 
Error:Execution failed for task ':mobile:transformClassesWithJarMergingForDebug'.

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/apache/poi/POIXMLDocument.class

Btw, this code:

project.tasks.withType(com.android.build.gradle.tasks.Dex) {
        additionalParameters=['--core-library'] // --core-library option needed for now, will fix it soon
    }

is not working. It throws the error 
Could not find property 'com' on com.android.build.gradle.AppExtension_Decorated@d2d97f

**Comment by andruhon** [comment]
https://github.com/andruhon/android5xlsx/issues/2 seems to be the same. Looking at it now

**Comment by andruhon** [comment]
Created config which works more consistently with sane minSdk and android gradle 1.3.0

**Comment by andruhon** [comment]
Sorry. The fix above only fixes --core-library issue.

It is not expected to work with this scratchpad in this way because this jars contain poi HSSF itself and scratchpad has it as a dependency, so it pulls it as well.
1. You can remove redundant classes from jars; 
2. put normal POI libraries into libs:
   poi-3.12-20150511.jar
   poi-ooxml-3.12-20150511.jar
   poi-ooxml-schemas-3.12-20150511.jar
   stax-1.2.0.jar
   stax-api-1.0.1.jar
   xmlbeans-2.6.0.jar (Only one extra thing you need to do is to re-pack the xmlbeans-2.6.0.jar to get rid of duplicates)

**Comment by Deno92** [comment]
Hi, I am working right now on this issue.
I've added like you said every single file. But when I want to create Workbook (Workbook wb = new XSSFWorkbook(stream); ) It fails everytime :(

I've tested it also like this: Workbook wb = WorkbookFactory.create(stream); but without success.

ErrorMessage:
FATAL EXCEPTION: main
Process: ch.dictit.nb.excelplugin, PID: 28807
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/xmlbeans/XmlOptions;

Even I have the xmlbeans-2.6.0.jar added in my project. Can you please help me?

**Comment by andruhon** [comment]
It seems like xmlbeans did not join the project. Could you please create a synthetic example and share it with me, so I can review it?

**Comment by Deno92** [comment]
Sure I've uploaded it here: https://drive.google.com/file/d/0B7TC1hJP0UN3NXhKRV8wbnRGQm8/view?usp=sharing

**Comment by andruhon** [comment]
@Deno92 I can confirm, that I have the same issue. It is, probably, something to do with how current version version of Android Studio works. I've created even more simple example and it can't find XSSFWorkbook despite of the fact that it is definitely in the jar. It needs some more serious investigation. Maybe I'll check that next week.

**Comment by Deno92** [comment]
Thank you so much for your help =)
I will check this too :)

**Comment by andruhon** [comment]
@Deno92 it is definitely something to do with tools. I've just checked the project which has been working properly before and now it does not after I built it with current android stuff. 
Maybe you try xlsx4j from http://www.docx4java.org/trac/docx4j ?

**Comment by andruhon** [comment]
@Deno92 , please check the lattest commit. I've applied javax -> aavax hack to my jars, no more need in --core-library mangling, you just need these two jars.

**Comment by Deno92** [comment]
@andruhon Okay thank you :) I am just working on it! I will keep you updated.

**Comment by Deno92** [comment]
@andruhon I've checkd it with your latest project and it works now! Thank you so much :)

**Comment by andruhon** [comment]
@Deno92 You're welcome!

**Comment by timkoers** [comment]
So the Apache poi module has been added? 😀

**Comment by andruhon** [comment]
@timkoers sorry, it was discussion about general defect which, I think, irrelevant to scratchpad. Do you still have some problems with scratchpad on android?

**Comment by timkoers** [comment]
@andruhon Sorry for the late reaction, yes I do. I can't use the latest version of scratchpad and the textstyle is returning the localized string of the applied style. Useless to me.

**Comment by andruhon** [comment]
@timkoers does it work for you on desktop JVM?
