### ISSUE TITLE
DOCX support?

### ISSUE THREAD

**Issue by mancvso** [andruhon/android5xlsx#17]
First, thanks for this code!

I have a weid use case where I have to read from XLSX and generate DOCX, but now I have a pretty

```
error: cannot access Paragraph
class file for org.apache.poi.wp.usermodel.Paragraph not found
```

on build time.

Any hint?

**Comment by andruhon** [comment]
No, this one does not contain HWPF/XWPF, only HSSF/XSSF, however you can try similar approach.
