### ISSUE TITLE
Getting Could not find property 'com' error

### ISSUE THREAD

**Issue by razelsoco** [andruhon/android5xlsx#2]
![screen shot 2016-01-26 at 3 02 55 pm](https://cloud.githubusercontent.com/assets/1171866/12574335/023cb4aa-c43e-11e5-8c4a-36f772458f39.png)

My build.gradle is already the same as the one in the  repo. 
How to solve this error?

**Comment by andruhon** [comment]
Hi! Could you please provide more details?

**Comment by andruhon** [comment]
I'll try to build it myself with the latest android studio, to see how it goes.

**Comment by razelsoco** [comment]
hey,
thanks for your supprt. actually i figured it out. i changed my gradle version from 1.5.0 to 1.3.0
now, i have another error,  adding '--core-library' does not seem to work for me..

i already added 
    project.tasks.withType(com.android.build.gradle.tasks.Dex) {
        additionalParameters=['--core-library'] // --core-library option needed for now, will fix it soon
    }

but still i got this:

However, you might actually be trying to define a class in a core
This is often due to inadvertently including a core library file
compatibility of your app with future versions of the platform.
in your application's project, when using an IDE (such as
going on.
core class, then this is the most likely explanation of what's
Eclipse). If you are sure you're not intentionally defining a
trouble processing "javax/xml/namespace/NamespaceContext.class":
assuredly not work. At a minimum, it jeopardizes the
It is also often of questionable legality.
this warning is that reflective operations on this class will incorrectly
from a non-Android virtual machine project. This will most
namespace, the source of which you may have taken, for example,
indicate that it is _not_ an inner class.
when not building a core library.
Ill-advised or mistaken usage of a core class (java.\* or javax.*)
appropriate as part of creating a full virtual machine
If you really intend to build a core library -- which is only
distribution, as opposed to compiling an application -- then use
the "--core-library" option to suppress this error message.

**Comment by razelsoco** [comment]
i got rid of the error by changing android minSdk from 21 to 16

**Comment by andruhon** [comment]
That's wired.

**Comment by andruhon** [comment]
It is crashing on preDex for which it is impossible to use --core-library. However it doesn't do preDex if min sdk is 16. I don't have explanation for that. That's weird.

However this build will not really work on sdk 16(android 4) because ART is not enabled there by default.

**Comment by andruhon** [comment]
Created config which works more consistently with sane minSdk and android gradle 1.3.0
