### ISSUE TITLE
Building APK

### ISSUE THREAD

**Issue by abbasiehsan1991** [andruhon/android5xlsx#9]
Hello
I used this in my project and now my application is complete now . But when i want to build an APK file 
android studio gives me some errors l
Please help me ,this is important to me.
Thankyou
![1](https://cloud.githubusercontent.com/assets/23223511/19948338/5201f9ea-a161-11e6-8e98-b7f20dc94bd0.PNG)
![2](https://cloud.githubusercontent.com/assets/23223511/19948340/555b84c6-a161-11e6-983d-3b5ae5d733e3.PNG)

**Comment by centic9** [comment]
The item about too less heap memory seems to be the actual issue here, you will need to adjust this in IntelliJ settings, not sure where exactly. 

The warning about inner Class also appears when things run fine.
